apiVersion: v1
kind: Namespace
metadata:
  name: devtroncd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: devtroncd
spec:
  targetNamespaces:
  - devtroncd
---


apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: devtroncd
spec:
  channel: alpha
  name: argocd-operator-helm
  source: operatorhubio-catalog
  sourceNamespace: olm
